version: '1'

services:
  coffee-shop:
    image: peterkulko/coffee-shop
    restart: always
    ports:
      - '3000:3000'
  coffee-shop-backend:
    image: peterkulko/coffee-shop-backend
    restart: always
    ports:
      - '4444:4444'
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_data_pub:/var/lib/mongo
volumes:
  mongo_data_pub:
